import fs from "fs";

const env = `
PORT=${process.env.PORT}
DATABASE_URI=${process.env.DATABASE_URI}
PAYLOAD_SECRET=${process.env.PAYLOAD_SECRET}
CLOUDFLARE_ACCOUNT_ID=${process.env.CLOUDFLARE_ACCOUNT_ID}
CLOUDFLARE_ACCESS_KEY_ID=${process.env.CLOUDFLARE_ACCESS_KEY_ID}
CLOUDFLARE_SECRET_ACCESS_KEY=${process.env.CLOUDFLARE_SECRET_ACCESS_KEY}
CLOUDFLARE_BUCKET_NAME=${process.env.CLOUDFLARE_BUCKET_NAME}
CLOUDFLARE_BUCKET_PUBLIC_LINK=${process.env.CLOUDFLARE_BUCKET_PUBLIC_LINK}
CLOUDFLARE_REGION=${process.env.CLOUDFLARE_REGION}
NEXT_PUBLIC_BUILD_DATE=${process.env.NEXT_PUBLIC_BUILD_DATE}
MIXPANEL_TOKEN=${process.env.MIXPANEL_TOKEN}
`;

fs.writeFileSync(".env", env);
console.log(".env file created");
