import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "selector",
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      sans: [
        "var(--font-neue-montreal)",
        "-apply-system",
        "Helvetica",
        "Arial",
      ],
      mono: ["var(--font-neue-montreal-mono)", "Roboto Mono"],
    },
    opacity: {
      "0": "var(--opacity-0)",
      "20": "var(--opacity-20)",
      "40": "var(--opacity-40)",
      "60": "var(--opacity-60)",
      "80": "var(--opacity-80)",
      "100": "var(--opacity-100)",
    },
    colors: {
      neutral: {
        100: "hsla(var(--primitive-100) / <alpha-value>)",
        200: "hsla(var(--primitive-200) / <alpha-value>)",
        300: "hsla(var(--primitive-300) / <alpha-value>)",
        400: "hsla(var(--primitive-400) / <alpha-value>)",
        500: "hsla(var(--primitive-500) / <alpha-value>)",
        600: "hsla(var(--primitive-600) / <alpha-value>)",
        700: "hsla(var(--primitive-700) / <alpha-value>)",
        800: "hsla(var(--primitive-800) / <alpha-value>)",
        900: "hsla(var(--primitive-900) / <alpha-value>)",
        1000: "hsla(var(--primitive-1000) / <alpha-value>)",
        1100: "hsla(var(--primitive-1100) / <alpha-value>)",
        1200: "hsla(var(--primitive-1200) / <alpha-value>)",
      },
    },
    backgroundColor: {
      DEFAULT: "hsla(var(--bg-default) / <alpha-value>)",
      subtle: "hsla(var(--bg-subtle) / <alpha-value>)",
      inverse: "hsla(var(--bg-inverse) / <alpha-value>)",
      success: "hsla(var(--utility-success) / <alpha-value>)",
      danger: "hsla(var(--utility-danger) / <alpha-value>)",
    },
    textColor: {
      DEFAULT: "hsla(var(--fg-default) / <alpha-value>)",
      subtle: "hsla(var(--fg-subtle) / <alpha-value>)",
      inverse: "hsla(var(--fg-inverse) / <alpha-value>)",
    },
    fill: {
      DEFAULT: "hsla(var(--fg-default) / <alpha-value>)",
      subtle: "hsla(var(--fg-subtle) / <alpha-value>)",
      inverse: "hsla(var(--fg-inverse) / <alpha-value>)",
    },
    borderRadius: {
      none: "0",
      "2px": "2px",
      "4px": "4px",
      "6px": "6px",
      "8px": "8px",
      "10px": "10px",
      "12px": "12px",
      "14px": "14px",
      "16px": "16px",
      "20px": "20px",
      "24px": "24px",
      full: "100%",
    },
    borderColor: {
      DEFAULT: "var(--border-default)",
      inverse: "var(--border-inverse)",
    },
    fontSize: {
      caption: ["0.75rem", "0.875rem"],
      body: ["0.875rem", "1rem"],
      "body-large": ["1rem", "1.125rem"],
      lead: ["1.375rem", "1.5rem"],
      heading: ["1.75rem", "2.625rem"],
      display: ["2.875rem", "3.25rem"],
    },
    spacing: {
      "0px": "var(--spacing-0px)",
      "2px": "var(--spacing-2px)",
      "4px": "var(--spacing-4px)",
      "6px": "var(--spacing-6px)",
      "8px": "var(--spacing-8px)",
      "10px": "var(--spacing-10px)",
      "12px": "var(--spacing-12px)",
      "14px": "var(--spacing-14px)",
      "16px": "var(--spacing-16px)",
      "18px": "var(--spacing-18px)",
      "20px": "var(--spacing-20px)",
      "24px": "var(--spacing-24px)",
      "28px": "var(--spacing-28px)",
      "30px": "var(--spacing-30px)",
      "40px": "var(--spacing-40px)",
      "60px": "var(--spacing-60px)",
      "80px": "var(--spacing-80px)",
    },
  },
  plugins: [],
};
export default config;
