export const MetadataSeed = {
  category: "Portfolio, Personal Website, Product Design, Web Development",
  generator: "Next.js",
  applicationName: "Mark Noya's Design Portfolio",
  keywords: [
    "Product Design",
    "Web Development",
    "Design Systems",
    "UI/UX Design",
    "User Interface Design",
    "User Experience",
    "Frontend Development",
    "Responsive Design",
    "Figma",
    "React",
    "Next.js",
    "JavaScript",
    "CSS",
    "Tailwind CSS",
    "HTML5",
    "Prototyping",
    "Wireframing",
    "Design Systems",
    "E-commerce Design",
    "Mobile App Design",
    "Interaction Design",
    "Web Applications",
    "Visual Design",
    "Accessibility",
    "SEO Best Practices",
    "Design Thinking",
    "User Research",
    "Portfolio Design",
  ],
  authors: [
    { name: "Mark Noya", url: "https://www.linkedin.com/in/mark-noya/" },
  ],
  creator: "Mark Noya",
  publisher: "Mark Noya",
  metadataBase: new URL("https://www.marknoya.me"),
  formatDetection: {
    email: true,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-image-preview": "large",
      "max-snippet": 300,
    },
  },
};
